set nocompatible
filetype off
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" Vundle has to manage Vundle.
Plugin 'gmarik/Vundle.vim'

Plugin 'bling/vim-airline'
" Syntax checking
Plugin 'scrooloose/syntastic'
Plugin 'editorconfig/editorconfig-vim'
" Plugin 'Valloric/YouCompleteMe'
Plugin 'altercation/vim-colors-solarized'
" Svn and Git gutters
Plugin 'mhinz/vim-signify'

" Enable file type detection. Do this after Vundle calls.
call vundle#end()
filetype plugin indent on


" status bar
" set statusline=%F%m%r%h%w\  "fullpath and status modified sign
set statusline=%f%m%r%h%w\  "path and status modified sign
set statusline+=\ %y "filetype
set statusline+=%=
set statusline+=\ [%l\/%L:\%v] "line number and column number

" Use the poweline fonts to make airline pretty
let g:airline_powerline_fonts = 1

" auto load files if vim detects they have been changed outside of Vim
set autoread

set nocompatible

" Allow backspace in insert mode
set backspace=indent,eol,start

" Centralize backups, swapfiles and undo history
set backupdir=~/.vim/backups
set directory=~/.vim/swaps
if exists("&undodir")
	set undodir=~/.vim/undo
endif

" allow unsaved background buffers and remember marks/undo for them
set hidden

" remember more commands and search history
if &history < 1000
  set history=1000
endif

" allow more tabs
if &tabpagemax < 50
  set tabpagemax=50
endif

" always show the status line
set laststatus=2

" Don't use spacing when hitting the tab key
set noexpandtab
set tabstop=4
set shiftwidth=4
set softtabstop=4
set smarttab

" show search matches as I type
set showmatch
set incsearch
set hlsearch

" make searches case-sensitive only if they contain upper-case characters
set ignorecase smartcase

" Prevent Vim from clobbering the scrollback buffer. See
" http://www.shallowsky.com/linux/noaltscreen.html
set t_ti= t_te=

" display incomplete commands
set showcmd

" Enable highlighting for syntax
syntax on

" Enable file type detection.
filetype plugin indent on

" enhance cli completion
set wildmenu

" Better tab completion
set wildmode=longest,list

" Line numbers
set number

" Use relative line numbers
if exists("&relativenumber")
	set relativenumber
	au BufReadPost * set relativenumber
endif

" Start scrolling three lines before the horizontal window border
set scrolloff=3

" pretty colours
set term=xterm-256color
colorscheme solarized
set background=dark
"set t_Co=256
" Colors for vim-airline
let g:airline_theme='solarized'

" highlight trailing whitespace
highlight ExtraWhitespace ctermbg=red guibg=red
autocmd BufWinEnter * match ExtraWhitespace /\s\+$/
match ExtraWhitespace /\s\+$/
autocmd BufWinEnter * match ExtraWhitespace /\s\+$/
autocmd InsertEnter * match ExtraWhitespace /\s\+\%#\@<!$/
autocmd InsertLeave * match ExtraWhitespace /\s\+$/
autocmd BufWinLeave * call clearmatches()

" reselect visual block after indent/outdent
vnoremap < <gv
vnoremap > >gv

" Set up vertical ruler at 80 characters in
if exists('+colorcolumn')
	set colorcolumn=80,100
endif

" highlight current line
set cursorline

" turn on auto indentation
set autoindent

" Handle SISTEM Managers crazy file types
au BufNewFile,BufRead *.phph set filetype=php
au BufNewFile,BufRead *.php3 set filetype=php
au BufNewFile,BufRead *.html set filetype=php
au BufNewFile,BufRead *.phtml set filetype=php
au BufNewFile,BufRead *.rgt setf rgt

" Json is just javasccript
autocmd BufNewFile,BufRead *.json set ft=javascript

" Try to find the tags file
set tags=tags\ /usr/lib/tags\ ../tags\ public/tags\ ./public/tags

" Sudo write (,W)
noremap <leader>W :w !sudo tee %<CR>

" Limit to svn and git
let g:signify_vcs_list = [ 'svn', 'git' ]
